### ISSUE TITLE
role="presentation" or "button" not helping with no-static-element-interactions error

### ISSUE THREAD

**Issue by valentinaAl** [evcohen/eslint-plugin-jsx-a11y#596] opened 2019-06-06 14:01 UTC
Hi! I'm having an issue that really looks like this other one [#214](https://github.com/evcohen/eslint-plugin-jsx-a11y/issues/214) I have the following element:

`<div
        onKeyDown={this.handleCloseWithKey}
      >`

That what it does is to close the div with esc key, the component looks like a dropdown, and if I move this event to the children wont work as expected, and if I also add 

`onClick={onClickHandler}
  onKeyPress={onKeyPressHandler}
  role="button"
  tabIndex="0" `

I get the same error, as well as if I add role="presentation"

I'm using eslint-config-airbnb as well as the issue linked at the beginning, and my package.json looks like this:
`[EDIT]`
` "eslint": "^5.16.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-loader": "^2.1.2",
    "eslint-plugin-import": "^2.17.2",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-react": "^7.13.0",`

Thanks in advance!

**Comment by valentinaAl** [comment] 2019-06-06 14:02
@ljharb here I create the issue, thank you!

**Comment by ljharb** [comment] 2019-06-06 15:56
That says 2.2.2 of this plugin; can you update it to the latest (v6) and try again?

You’ll also want to update eslint from v3 to v5, and the Airbnb config from v12 to v17

In other words, the problem is likely because you haven’t updated to a new enough version to include that bug fix.

**Comment by valentinaAl** [comment] 2019-06-06 16:02
Oh my bad, I checkout other branch and mistake, but I do have updated to those versions, I'll edit the issue sorry

**Comment by jessebeach** [comment] 2019-06-23 22:59
#605 adds a test case that passes. @valentinaAl I'm going to close this issue unless you have a test case that fails.

**Closed by jessebeach** 2019-06-23 22:59 UTC

**Comment by valentinaAl** [comment] 2019-06-26 19:43
Thanks, I will check again in a few days, but, I can't really tell why there is an error, if there is a role="presentation" along a onKeyDown event, thank you for your time
