### ISSUE TITLE
accessible-emoji complains about copyright

### ISSUE THREAD

**Issue by badtant** [evcohen/eslint-plugin-jsx-a11y#184] opened 2017-02-23 10:00 UTC
&copy; Somthing something

This isn't an emoji? :)

**Comment by evcohen** [comment] 2017-02-23 18:46
It actually is! Emojis are just unicode characters. See: [Copyright unicode](http://unicode.org/emoji/charts/full-emoji-list.html#00a9)

This is also a duplicate of #180

**Closed by evcohen** 2017-02-23 18:46 UTC
