### ISSUE TITLE
Flow issues in 5.0.1

### ISSUE THREAD

**Issue by leos** [evcohen/eslint-plugin-jsx-a11y#242] opened 2017-05-15 12:31 UTC
It looks like a couple of the rules in 5.0.1 are missing type imports:

```
node_modules/eslint-plugin-jsx-a11y/src/rules/interactive-supports-focus.js:46
 46:   create: (context: ESLintContext) => ({
                         ^^^^^^^^^^^^^ identifier `ESLintContext`. Could not resolve name

node_modules/eslint-plugin-jsx-a11y/src/rules/media-has-caption.js:43
 43:   create: (context: ESLintContext) => ({
                         ^^^^^^^^^^^^^ identifier `ESLintContext`. Could not resolve name

node_modules/eslint-plugin-jsx-a11y/src/rules/no-interactive-element-to-noninteractive-role.js:47
 47:   create: (context: ESLintContext) => {
                         ^^^^^^^^^^^^^ identifier `ESLintContext`. Could not resolve name

node_modules/eslint-plugin-jsx-a11y/src/rules/no-interactive-element-to-noninteractive-role.js:51
 51:         attribute: ESLintJSXAttribute,
                        ^^^^^^^^^^^^^^^^^^ identifier `ESLintJSXAttribute`. Could not resolve name

node_modules/eslint-plugin-jsx-a11y/src/rules/no-noninteractive-element-interactions.js:46
 46:   create: (context: ESLintContext) => {
                         ^^^^^^^^^^^^^ identifier `ESLintContext`. Could not resolve name

node_modules/eslint-plugin-jsx-a11y/src/rules/no-noninteractive-element-to-interactive-role.js:47
 47:   create: (context: ESLintContext) => {
                         ^^^^^^^^^^^^^ identifier `ESLintContext`. Could not resolve name

node_modules/eslint-plugin-jsx-a11y/src/rules/no-noninteractive-element-to-interactive-role.js:51
 51:         attribute: ESLintJSXAttribute,
                        ^^^^^^^^^^^^^^^^^^ identifier `ESLintJSXAttribute`. Could not resolve name

node_modules/eslint-plugin-jsx-a11y/src/rules/no-noninteractive-tabindex.js:46
 46:   create: (context: ESLintContext) => {
                         ^^^^^^^^^^^^^ identifier `ESLintContext`. Could not resolve name

node_modules/eslint-plugin-jsx-a11y/src/rules/no-static-element-interactions.js:47
 47:   create: (context: ESLintContext) => {
                         ^^^^^^^^^^^^^ identifier `ESLintContext`. Could not resolve name
```

**Comment by ljharb** [comment] 2017-05-15 14:38
Duplicate of #241.

**Closed by ljharb** 2017-05-15 14:38 UTC
