### ISSUE TITLE
Allow anchors with # href if they have no onClick handler

### ISSUE THREAD

**Issue by TomasHubelbauer** [evcohen/eslint-plugin-jsx-a11y#580] opened 2019-04-02 14:41 UTC
I want a navigatable link which takes one to the top of the page, not to any specific anchor. I am using `<a href="#">` for that, like I do for any other section (`<a href="#section">`). I understand the rationale behind disallowing `#` on anchors with `onclick` handlers, because they misuse the anchors, but `#` with no `onclick` sounds like a perfectly valid use case for me - it takes you to a section with no name, which also happens to scroll the browser all the way up.

**Comment by ljharb** [comment] 2019-04-02 15:37
Duplicate of #555.

Try `#top`.

**Closed by ljharb** 2019-04-02 15:37 UTC

**Comment by TomasHubelbauer** [comment] 2019-04-02 15:44
Didn't know about `#top`, thanks.
